<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{9125b42d-76e9-46bb-903f-a0fc0ca68154}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Controller : ConveyorController;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Controller();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>